# This is a basic workflow that is manually triggered

name: CD

on:
  push:
    branches:
      - "main"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
#       - name: Decrypt Android keys
#         run: sh ./.github/scripts/decrypt_android_keys.sh
#         env:
#           ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3
      - name: Install Flutter dependencies
        run: flutter pub get

#       - name: Analyze files
#         run: flutter analyze .
#       - name: Run the tests
#         run: flutter test
      - name: Build the debug APK
        run: flutter build apk --debug
      - name: publish debug results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk

      - name: Generate Diawi link
        uses: rnkdsh/action-upload-diawi@v1.2.1
        id: diawi
        with:
          token: QWSoA8AXT4j766Y9hgNUSOHs2bgE0hWCuMdMyFkMFv
          file: build/app/outputs/apk/debug/app-debug.apk
          comment: 'Uploaded from Github Action'
          recipients: gajjarmail07@gmail.com
      
      - name: Output
        run: echo "Diawi URL = ${{ steps.diawi.outputs['url'] }}"
        
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
#           username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
#           password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: gajjarmail07@gmail.com
          # Required sender full name (address can be skipped):
          from: Chirag Sondagar # <sondagar143@gmail.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: "Diawi URL = ${{ steps.diawi.outputs['url'] }}"
          # Optional carbon copy recipients:
#           cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
#           bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
#           reply_to: luke@example.com
          # Optional Message ID this message is replying to:
#           in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: build/app/outputs/apk/debug/app-debug.apk
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
