# This is a basic workflow that is manually triggered

name: CD

on:
  push:
    branches:
      - "main"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
#       - name: Decrypt Android keys
#         run: sh ./.github/scripts/decrypt_android_keys.sh
#         env:
#           ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3
      - name: Install Flutter dependencies
        run: flutter pub get

#       - name: Analyze files
#         run: flutter analyze .
#       - name: Run the tests
#         run: flutter test
      - name: Build the debug APK
        run: flutter build apk --debug
      - name: publish debug results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
      - name: Build the release APK
        run: flutter build apk --release
      - name: publish release results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
